### ISSUE TITLE
Question: Can I still use Spring MVC for my REST endpoints?

### ISSUE THREAD

**Issue by kurron** [dsyer/spring-boot-ratpack#3]
We're a Spring Boot shop and rely heavily on Spring MVC for our REST endpoints.  We use Boot and embedded Tomcat for a self-hosting JAR.  Is it possible to replace Tomcat with Ratback while still keeping all my Spring MVC code in place?  I am afraid that SMVC is tied into the servlet spec somehow and would not run without a servlet container.

**Comment by dsyer** [comment]
No, Spring MVC has a completely different programming model. This project is never going to deliver @MVC on top of ratpack (it's a square peg in a round hole).
