### ISSUE TITLE
Is there any plan to upgrade ratpack from 0.9.12 to 0.9.13?

### ISSUE THREAD

**Issue by lks21c** [dsyer/spring-boot-ratpack#4]
Hi, I analyzed and reviewed this code  usefully.

And I tried to upgrade Ratpack's module to 0.9.13 since it was release on 2015-01-31.

But upgrading the code wasn't easy since Ratpack's “launch” layer was completely re-written.
http://www.ratpack.io/versions/0.9.13

So I'm curious you intend to upgrade this source code to 0.9.13.
Thanks for reading this. :)

**Comment by dsyer** [comment]
In the process of upgrading to 0.9.15 now.

**Comment by dsyer** [comment]
Upgrade almost complete, but master has 0.9.15 on it now. CLI not working apparently.
